### PR TITLE
Fix/presist settings

### LINKED ISSUE #241: [Bug] Changes to settings are not persisted/saved permanently
**Describe the bug**
See: https://walletconnect.slack.com/archives/C044SKFKELR/p1695391725780119

**To Reproduce**
1. Change a setting
2. Refresh
3. Setting is back in default state

**Expected behavior**
Changes to settings applied by the user are saved permanently/persisted.

### PR DESCRIPTION
**Pull request by devceline**
# Description

- Persist *all* `SettingsContext` settings in `localStorage`.
- On `SettingsContextProvider` init, use persisted settings.
- Remove `favoriteTheme` web3modal references as they were completely unused and we no longer need to persist `w3i-theme` by itself.

# Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Draft PR (breaking/non-breaking change which needs more work for having a proper functionality _[Mark this PR as ready to review only when completely ready]_)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Fixes/Resolves (Optional)

Resolves #241 

# Checklist:

- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/contexts/SettingsContext/index.tsx [hunk 1]
```diff
@@ -16,32 +17,27 @@ const settingsReducer = (
...
-    typeof localStorage === 'undefined' || !localStorage
-      ? null
-      : (localStorage.getItem('w3i-theme') as SettingsContextSimpleState['mode'] | null)
+  const localSettings = localStorage.getItem(LOCAL_SETTINGS_KEY)
 
-  const initialState: SettingsContextSimpleState = {
+  const initialState: SettingsContextSimpleState = localSettings? JSON.parse(localSettings) : {
     mode: 'light',
     newContacts: 'require-invite',
     isDevModeEnabled: true
```
Comment (chris13524) [inline src/contexts/SettingsContext/index.tsx:25]: Can we default to false?

Comment (devceline) [reply src/contexts/SettingsContext/index.tsx]: Done.

**Review by Cali93 — APPROVED** [review]
🏎️
